### ISSUE TITLE
Keyboard.clears mentioned in README

### ISSUE THREAD

**Issue by 2mol** [ohanhi/keyboard#10]
As far as I can see `Keyboard.clears` doesn't exist (anymore?). Is these something else that should be mentioned in the readme, or can it be removed?

**Comment by ohanhi** [comment]
Oh yeah. This was something I thought would get fixed soon after the 0.19 release. The issue was that [Browser.Events.onVisibilityChange](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onVisibilityChange) did not trigger because of a typo in the source code, so I removed the feature from Keyboard in the meantime. Could you check if the events work nowadays? I'd rather add the feature than remove the mention from the readme.

**Comment by 2mol** [comment]
I _think_ that fix is why `Browser` was bumped to 1.0.1, see here: https://github.com/elm/browser/commit/c1475216206d49a0616e9cd1fa2149a4f095df03

So I think it's fair to assume it's fixed. Otherwise Evan also has a minimal example here, to test it: https://github.com/elm/browser/issues/21#issuecomment-415404790

**Comment by Birowsky** [comment]
@2mol care to share what'd you end up doing?

Are you clearing the state on `onVisibilityChange`?

**Comment by ohanhi** [comment]
Sorry for not coming back to you, but I couldn't get the `onVisibilityChange` to work. Not even using the SSCE. The MDN examples on the Page Visibility API do work though, so I'm a bit confused as to what to do now.

**Comment by FranzSkuffka** [comment]
Evan's SSCE works for me when I paste the code in https://elm-lang.org/examples/hello. 
Renders: `[Visible,Hidden,Visible,Hidden,Visible,Hidden]`.

**Comment by ohanhi** [comment]
This is finally fixed. I removed all references to `clears` and added a section about `window.onblur` to the README as well. This is published as 2.0.1. 

Again, thanks for noticing this and helping me out!
